# Etape 1.1 - Exploration des csv

In [1]:
import pandas as pd
import numpy as np

## caracteristics.csv

In [10]:
df_caracteristics = pd.read_csv("../src/data/data_kaggle/caracteristics.csv", encoding="latin1")

C:\Users\sebas\AppData\Local\Temp\ipykernel_6116\3079145501.py:1: DtypeWarning: Columns (0: long) have mixed types. Specify dtype option on import or set low_memory=False.
  df_caracteristics = pd.read_csv("../src/data/data_kaggle/caracteristics.csv", encoding="latin1")

In [13]:
df_caracteristics.loc[df_caracteristics.Num_Acc == 200800028239]

,Num_Acc,an,mois,jour,hrmn,lum,agg,int,atm,col,com,adr,gps,lat,long,dep
537587,200800028239,8,5,22,2315,3,1,1,1.0,6.0,516.0,NaN,M,0.0,0.0,310

In [12]:
df_caracteristics.head()

,Num_Acc,an,mois,jour,hrmn,lum,agg,int,atm,col,com,adr,gps,lat,long,dep
0,201600000001,16,2,1,1445,1,2,1,8.0,3.0,5.0,"46, rue Sonneville",M,0.0,0.0,590
1,201600000002,16,3,16,1800,1,2,6,1.0,6.0,5.0,1a rue du cimetière,M,0.0,0.0,590
2,201600000003,16,7,13,1900,1,1,1,1.0,6.0,11.0,NaN,M,0.0,0.0,590
3,201600000004,16,8,15,1930,2,2,1,7.0,3.0,477.0,52 rue victor hugo,M,0.0,0.0,590
4,201600000005,16,12,23,1100,1,2,3,1.0,3.0,11.0,rue Joliot curie,M,0.0,0.0,590

In [17]:
df_caracteristics.int.unique()

array([1, 6, 3, 2, 9, 8, 4, 7, 5, 0])

In [28]:
df_caracteristics.info()

<class 'pandas.DataFrame'>
RangeIndex: 839985 entries, 0 to 839984
Data columns (total 16 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Num_Acc  839985 non-null  int64
 1   an       839985 non-null  int64
 2   mois     839985 non-null  int64
 3   jour     839985 non-null  int64
 4   hrmn     839985 non-null  int64
 5   lum      839985 non-null  int64
 6   agg      839985 non-null  int64
 7   int      839985 non-null  int64
 8   atm      839930 non-null  float64
 9   col      839974 non-null  float64
 10  com      839983 non-null  float64
 11  adr      699443 non-null  str
 12  gps      366226 non-null  str
 13  lat      362471 non-null  float64
 14  long     362467 non-null  object
 15  dep      839985 non-null  int64
dtypes: float64(4), int64(9), object(1), str(2)
memory usage: 102.5+ MB

In [45]:
df_caracteristics.atm.unique()

array([ 8.,  1.,  7.,  9.,  5.,  2.,  3.,  6.,  4., nan])

## holidays.csv

In [24]:
df_holidays = pd.read_csv("../src/data/data_kaggle/holidays.csv", encoding="latin1")

In [25]:
df_holidays

             ds                       holiday
0    2005-01-01                      New year
1    2005-03-28                 Easter Monday
2    2005-05-01                    Labour Day
3    2005-05-05            Ascension Thursday
4    2005-05-08         Victory in Europe Day
..          ...                           ...
127  2016-07-14                  Bastille Day
128  2016-08-15  Assumption of Mary to Heaven
129  2016-11-01                All Saints Day
130  2016-11-11                 Armistice Day
131  2016-12-25                 Christmas Day

[132 rows x 2 columns]

In [27]:
df_holidays.info()

<class 'pandas.DataFrame'>
RangeIndex: 132 entries, 0 to 131
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ds       132 non-null    str
 1   holiday  132 non-null    str
dtypes: str(2)
memory usage: 2.2 KB

## places.csv

In [30]:
df_places = pd.read_csv("../src/data/data_kaggle/places.csv", encoding="latin1")

C:\Users\sebas\AppData\Local\Temp\ipykernel_27456\985829435.py:1: DtypeWarning: Columns (0: voie) have mixed types. Specify dtype option on import or set low_memory=False.
  df_places = pd.read_csv("../src/data/data_kaggle/places.csv", encoding="latin1")

In [31]:
df_places

,Num_Acc,catr,voie,v1,v2,circ,nbv,pr,pr1,vosp,prof,plan,lartpc,larrout,surf,infra,situ,env1
0,201600000001,3.0,39,NaN,NaN,2.0,0.0,NaN,NaN,0.0,1.0,3.0,0.0,0.0,1.0,0.0,1.0,0.0
1,201600000002,3.0,39,NaN,NaN,1.0,0.0,NaN,NaN,0.0,1.0,2.0,0.0,58.0,1.0,0.0,1.0,0.0
2,201600000003,3.0,1,NaN,NaN,2.0,2.0,NaN,NaN,0.0,1.0,3.0,0.0,68.0,2.0,0.0,3.0,99.0
3,201600000004,4.0,0,NaN,NaN,2.0,0.0,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,99.0
4,201600000005,4.0,0,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
839980,200500087950,4.0,0.0,0.0,NaN,2.0,3.0,NaN,NaN,0.0,1.0,1.0,0.0,80.0,1.0,0.0,1.0,3.0
839981,200500087951,4.0,0.0,0.0,NaN,2.0,2.0,NaN,NaN,0.0,1.0,2.0,0.0,70.0,1.0,0.0,1.0,0.0
839982,200500087952,4.0,0.0,0.0,NaN,1.0,2.0,NaN,NaN,0.0,1.0,1.0,0.0,75.0,1.0,0.0,1.0,3.0
839983,200500087953,4.0,0.0,0.0,NaN,2.0,0.0,NaN,NaN,0.0,1.0,1.0,0.0,150.0,1.0,0.0,1.0,0.0
839984,200500087954,2.0,0.0,0.0,NaN,3.0,2.0,76.0,0.0,0.0,1.0,2.0,20.0,75.0,2.0,0.0,1.0,0.0

In [48]:
df_places.voie

0          39
1          39
2           1
3           0
4           0
         ...
839980    0.0
839981    0.0
839982    0.0
839983    0.0
839984    0.0
Name: voie, Length: 839985, dtype: object

In [32]:
df_places.info()

<class 'pandas.DataFrame'>
RangeIndex: 839985 entries, 0 to 839984
Data columns (total 18 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Num_Acc  839985 non-null  int64
 1   catr     839984 non-null  float64
 2   voie     780914 non-null  object
 3   v1       332816 non-null  float64
 4   v2       33953 non-null   str
 5   circ     839187 non-null  float64
 6   nbv      838195 non-null  float64
 7   pr       414770 non-null  float64
 8   pr1      413463 non-null  float64
 9   vosp     838345 non-null  float64
 10  prof     838924 non-null  float64
 11  plan     838909 non-null  float64
 12  lartpc   830440 non-null  float64
 13  larrout  831706 non-null  float64
 14  surf     838968 non-null  float64
 15  infra    838707 non-null  float64
 16  situ     838983 non-null  float64
 17  env1     838709 non-null  float64
dtypes: float64(15), int64(1), object(1), str(1)
memory usage: 115.4+ MB

## users.csv

In [8]:
df_users = pd.read_csv("../src/data/data_kaggle/users.csv", encoding="latin1")

In [34]:
df_users

,Num_Acc,place,catu,grav,sexe,trajet,secu,locp,actp,etatp,an_nais,num_veh
0,201600000001,1.0,1,1,2,0.0,11.0,0.0,0.0,0.0,1983.0,B02
1,201600000001,1.0,1,3,1,9.0,21.0,0.0,0.0,0.0,2001.0,A01
2,201600000002,1.0,1,3,1,5.0,11.0,0.0,0.0,0.0,1960.0,A01
3,201600000002,2.0,2,3,1,0.0,11.0,0.0,0.0,0.0,2000.0,A01
4,201600000002,3.0,2,3,2,0.0,11.0,0.0,0.0,0.0,1962.0,A01
...,...,...,...,...,...,...,...,...,...,...,...,...
1876000,200500087953,1.0,1,1,1,0.0,13.0,0.0,0.0,0.0,1972.0,B01
1876001,200500087953,1.0,1,1,1,0.0,13.0,0.0,0.0,0.0,1965.0,C01
1876002,200500087953,1.0,1,4,1,5.0,23.0,0.0,0.0,0.0,1990.0,A01
1876003,200500087954,1.0,1,4,1,0.0,13.0,0.0,0.0,0.0,1951.0,A01
1876004,200500087954,2.0,2,4,2,0.0,13.0,0.0,0.0,0.0,1946.0,A01

In [35]:
df_users.info()

<class 'pandas.DataFrame'>
RangeIndex: 1876005 entries, 0 to 1876004
Data columns (total 12 columns):
 #   Column   Dtype
---  ------   -----
 0   Num_Acc  int64
 1   place    float64
 2   catu     int64
 3   grav     int64
 4   sexe     int64
 5   trajet   float64
 6   secu     float64
 7   locp     float64
 8   actp     float64
 9   etatp    float64
 10  an_nais  float64
 11  num_veh  str
dtypes: float64(7), int64(4), str(1)
memory usage: 171.8 MB

In [16]:
df_users.loc[df_users.Num_Acc == 200800028239]

,Num_Acc,place,catu,grav,sexe,trajet,secu,locp,actp,etatp,an_nais,num_veh
1194707,200800028239,1.0,1,1,1,5.0,11.0,0.0,0.0,0.0,1949.0,A01
1194708,200800028239,2.0,2,1,2,0.0,11.0,0.0,0.0,0.0,1946.0,A01
1194709,200800028239,0.0,3,3,1,5.0,0.0,1.0,9.0,1.0,1987.0,A02

## vehicle.csv

In [2]:
df_vehicles = pd.read_csv("../src/data/data_kaggle/vehicles.csv", encoding="latin1")

In [3]:
df_vehicles

              Num_Acc  senc  catv  occutc  obs  obsm  choc  manv num_veh
0        201600000001   0.0     7       0  0.0   0.0   1.0   1.0     B02
1        201600000001   0.0     2       0  0.0   0.0   7.0  15.0     A01
2        201600000002   0.0     7       0  6.0   0.0   1.0   1.0     A01
3        201600000003   0.0     7       0  0.0   1.0   6.0   1.0     A01
4        201600000004   0.0    32       0  0.0   0.0   1.0   1.0     B02
...               ...   ...   ...     ...  ...   ...   ...   ...     ...
1433384  200500087952   0.0     7       0  0.0   2.0   3.0   1.0     A01
1433385  200500087953   0.0     7       0  0.0   2.0   3.0  19.0     B01
1433386  200500087953   0.0     2       0  0.0   2.0   1.0  17.0     A01
1433387  200500087953   0.0     7       0  0.0   2.0   1.0   1.0     C01
1433388  200500087954   0.0     7       0  4.0   0.0   0.0   1.0     A01

[1433389 rows x 9 columns]

In [39]:
df_vehicles.info()

<class 'pandas.DataFrame'>
RangeIndex: 1433389 entries, 0 to 1433388
Data columns (total 9 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   Num_Acc  1433389 non-null  int64
 1   senc     1433317 non-null  float64
 2   catv     1433389 non-null  int64
 3   occutc   1433389 non-null  int64
 4   obs      1432627 non-null  float64
 5   obsm     1432788 non-null  float64
 6   choc     1433160 non-null  float64
 7   manv     1433083 non-null  float64
 8   num_veh  1433389 non-null  str
dtypes: float64(5), int64(3), str(1)
memory usage: 98.4 MB

In [15]:
df_vehicles.loc[df_vehicles.Num_Acc == 200800028239]

             Num_Acc  senc  catv  occutc  obs  obsm  choc  manv num_veh
914170  200800028239   0.0     7       0  0.0   1.0   1.0   1.0     A01

# Etape 1.2 - Lecture/traitement depuis la DataBase

In [9]:
import pandas as pd
import psycopg2
import xgboost as xgb
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_sample_weight

conn_params = {
    "dbname": "mlops_accidents",
    "user": "postgres",
    "password": "sebiback",
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**conn_params)

carac = pd.read_sql("SELECT * FROM caracteristics;", conn)
places = pd.read_sql("SELECT * FROM places;", conn)
vehicles = pd.read_sql("SELECT * FROM vehicles;", conn)
users = pd.read_sql("SELECT * FROM users;", conn)
conn.close()

df = users.merge(vehicles, on=["num_acc","num_veh"], how="left")\
          .merge(carac, on="num_acc", how="left")\
          .merge(places, on="num_acc", how="left")

df = df.drop_duplicates().dropna()
df = df[~df.isin(["-"]).any(axis=1)]

y = df["grav"].astype(int)
y = y - 1
X = df.drop(columns=["num_acc","num_veh","adr","lat","long", "dep","an_nais","place","voie","v1","v2","pr", "lartpc", "larrout","occutc","obs","grav"])

# Encodage catégories
for col in X.select_dtypes(include="object").columns:
    X[col] = X[col].astype("category").cat.codes
    
X = X.apply(pd.to_numeric, errors="coerce")
X = X.fillna(0)
X = X.astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = xgb.XGBClassifier(
    n_estimators     = 400,
    max_depth        = 8,
    learning_rate    = 0.05,
    subsample        = 0.8,
    colsample_bytree = 0.8,
    eval_metric      = "logloss",
    tree_method      = "hist",
    n_jobs           = -1,
    random_state     = 42,
    verbosity        = 0
)

sample_weights = compute_sample_weight(
                class_weight="balanced",
                y=y_train
)

C:\Users\sebas\AppData\Local\Temp\ipykernel_25040\1348642410.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  carac = pd.read_sql("SELECT * FROM caracteristics;", conn)
C:\Users\sebas\AppData\Local\Temp\ipykernel_25040\1348642410.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  places = pd.read_sql("SELECT * FROM places;", conn)
C:\Users\sebas\AppData\Local\Temp\ipykernel_25040\1348642410.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  vehicles = pd.read_sql("SELECT * FROM vehicles;", conn)
C:\Users\sebas\AppData\Local\Temp\ipykernel_25040\1348642410.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  users = pd.read_sql("SELECT * FROM users;", conn)
C:\Users\sebas\AppData\Local\Temp\ipykernel_25040\1348642410.py:37: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in X.select_dtypes(include="object").columns:

In [12]:
print(y.value_counts(normalize=True))

grav
0    0.409218
3    0.354546
2    0.209324
1    0.026912
Name: proportion, dtype: float64

In [11]:
model.fit(X_train, y_train, sample_weight=sample_weights)

y_pred = model.predict(X_test)

acc = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average="macro")

print("\n===== METRICS =====")
print(f"Accuracy : {acc:.4f}")
print(f"F1-score (macro) : {f1:.4f}")

print("\n===== CONFUSION MATRIX =====")
print(confusion_matrix(y_test, y_pred))

print("\n===== CLASSIFICATION REPORT =====")
print(classification_report(y_test, y_pred))

===== METRICS =====
Accuracy : 0.6201
F1-score (macro) : 0.5180

===== CONFUSION MATRIX =====
[[118138   7045   8918  16598]
 [   509   6445   2323    696]
 [  8180  20213  31153  17923]
 [ 27000   8723  22000  72986]]

===== CLASSIFICATION REPORT =====
              precision    recall  f1-score   support

           0       0.77      0.78      0.78    150699
           1       0.15      0.65      0.25      9973
           2       0.48      0.40      0.44     77469
           3       0.67      0.56      0.61    130709

    accuracy                           0.62    368850
   macro avg       0.52      0.60      0.52    368850
weighted avg       0.66      0.62      0.63    368850